<?php

use Illuminate\Database\Seeder;

class ActivityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Lance la génération de données en précisant le nombre à générer
        $Activity = [
            [
                'id_category' 		=> 1,
                'id_type' 			=> 1,
                'id_city' 			=> 2,
                'id_region' 		=> 1,
                'id_country' 		=> 1,
                'name' 				=> 'Saut en Parachute tandem',
                'description' 		=> 'Sauter en parachute est une expérience unique à vivre, les sensations sont intenses et l’impression de voler au milieu des nuages est extraordinaire. L’expérience est fabuleuse et la vitesse ressentie également pqrce que la personne approche les 300 km/h. Lors de votre premier saut en parachute laissez aux parachutistes professionnels qui vous accompagnent le soin de gérer votre sécurité. Vous serez pris en charge avant le saut et la seule chose qui vous reste alors à faire c’est : prendre du plaisir ! Offrez ou offrez-vous un cadeau avec un saut en parachute et réservez dès à présent partout en France pour pas cher : vous allez vivre une expérience unique avec un baptême de en air en saut en parachute! un cadeau idéal pour un enterrement de vie de jeune fille ou de garçon ! Découvrez vite la chute libre durant un week-end !',
                'amount'			=> 220,
                'image1_location'   => '/images/parachuteTandem1.jpg',
                'image2_location'   => '/images/parachuteTandem2.jpg',
                'image3_location'   => '/images/parachuteTandem3.jpg',
                'start' 			=> now(),
                'end' 				=> now(),
                'number_of_persons' => 2,
            ],
            [
                'id_category' 		=> 1,
                'id_type' 			=> 2,
                'id_city' 			=> 2,
                'id_region' 		=> 1,
                'id_country' 		=> 1,
                'name' 				=> 'Saut en Parachute PAC',
                'description' 		=> 'Vous êtes un amateur de sensations fortes ? Un baptême en tandem ou un saut dinitiation ne permet de assouvir pleinement votre quête de adrénaline ? Venez effectuer un stage de Progression accompagnée en chute (PAC) ! A la suite de une série de cours théoriques, vous effectuerez votre premier saut et goûterez au plaisir intense de la sensation de liberté s"offrant à vous. Seul lors de la phase de chute libre et de parachute ouvert, mais parfaitement encadré par une équipe de professionnels qualifiés dans les airs et au sol par assistance radio, vous progresserez rapidement. La phase apprentissage dure plusieurs jours et sera ponctuée de plusieurs sauts quotidiens. En devenant parachutiste, vous avez une opportunité de sauter en solo aux quatre coins du monde, alors vous attendez quoi pour choisir dans notre sélection le stage de saut en parachute idéal ?',
                'amount'			=> 1320,
                'image1_location'   => '/images/parachutePac1.jpg',
                'image2_location'   => '/images/parachutePac2.jpg',
                'image3_location'   => '/images/parachutePac3.jpg',
                'start' 			=> now(),
                'end' 				=> now(),
                'number_of_persons' => 1,
            ],
            [
                'id_category' 		=> 1,
                'id_type' 			=> 3,
                'id_city' 			=> 3,
                'id_region' 		=> 1,
                'id_country' 		=> 1,
                'name' 				=> 'Simulation chute libre',
                'description' 		=> 'Venez ressentir les premières sensations un saut en parachute sans quitter le plancher des vaches dans un simulateur de chute libre. Le principe est simple : il sagit de un grand tube de plexiglass équipé de une puissante soufflerie à sa base, reproduisant les effets de la résistance de air rencontrée lors de une véritable chute libre. Pas de sensations d accélération comme lors d un saut en parachute mais la soufflerie vous maintient bel et bien en l air et vous permet d appréhender les sensations d un saut. À l intérieur du simulateur vous serez encadré par un professionnel de la chute libre qui vous aidera à vous positionner pour rester stable, voire effectuer quelques mouvements ; ce qui est moins facile qu il y parait ! Plaisir et sensations fortes seront au rendez-vous ! attendez plus et réservez un saut en soufflerie !',
                'amount'			=> 60,
                'image1_location'   => '/images/simulateur1.jpg',
                'image2_location'   => '/images/simulateur2.jpg',
                'image3_location'   => '/images/simulateur3.jpg',
                'start' 			=> now(),
                'end' 				=> now(),
                'number_of_persons' => 1,
            ],
            [
                'id_category' 		=> 2,
                'id_type' 			=> 4,
                'id_city' 			=> 4,
                'id_region' 		=> 1,
                'id_country' 		=> 1,
                'name' 				=> 'Descente en Kayak à Gorge du Verdan',
                'description' 		=> "Venez vous évader grâce à une activité sportive, conviviale et ludique : le canoë kayak ! Débutant ou confirmé, en famille ou entre amis, on vous garantit un moment de détente loin du stress et des tracas quotidiens dans un univers bucolique. Un moment de pur bonheur et de pure convivialité, une aventure que vous souhaiterez vite réitérer. Vous découvrirez une nature insoupçonnée, un patrimoine naturel exceptionnel. Location de Kayak ou stage de canoë ou escapade en kayak… Vous trouverez votre bonheur dans la sélection suivante !",
                'amount'			=> 32,
                'image1_location'   => '/images/kayak1.jpg',
                'image2_location'   => '/images/kayak2.jpg',
                'image3_location'   => '/images/kayak3.jpg',
                'start' 			=> now(),
                'end' 				=> now(),
                'number_of_persons' => 2,
            ],
            [
                'id_category' 		=> 2,
                'id_type' 			=> 5,
                'id_city' 			=> 4,
                'id_region' 		=> 1,
                'id_country' 		=> 1,
                'name' 				=> 'Canoe biplace à Gorge du Verdon',
                'description' 		=> "Trouvez un stage en canoë encadré par des professionnels et des passionnés sur les plus belles rivières de France. Descendez des rivières mythiques et procurez-vous des sensations grâce à de petits rapides accessibles à tous. Partez à la rencontre de la nature comme vous ne l’avez encore jamais vue, en naviguant au cours d’une balade inoubliable sur des cours d’eau. Un gilet de sauvetage, une rame, un moniteur expérimenté et votre stage en canoë sera un moment dont vous vous souviendrez toute votre vie.",
                'amount'			=> 12,
                'image1_location'   => '/images/canoe1.jpg',
                'image2_location'   => '/images/canoe2.jpg',
                'image3_location'   => '/images/canoe3.jpg',
                'start' 			=> now(),
                'end' 				=> now(),
                'number_of_persons' => 1,
            ],
            [
                'id_category' 		=> 2,
                'id_type' 			=> 5,
                'id_city' 			=> 2,
                'id_region' 		=> 1,
                'id_country' 		=> 1,
                'name' 				=> 'Descente en  canyoning',
                'description' 		=>  "Le canyoning est une activité d’eaux vives consistant en une descente de canyon à pieds. Cette activité combine plusieurs disciplines telles que la spéléologie, la randonnée, et l’alpinisme. Durant cette activité vous descendrez des cascades en rappel, effectuerez des sauts, glisserez dans des toboggans naturels et découvrirez des gorges aussi impressionnantes que magnifiques. Que ce soit à Annecy, en Ardèche ou ailleurs, le canyoning c’est l’alliance entre sensations intenses et découverte de la nature. Découvrez sans attendre les offres que propose notre réseau de professionnels du canyoning.",
                'amount'			=> 52,
                'image1_location'   => '/images/canyoning1.jpg',
                'image2_location'   => '/images/canyoning2.jpg',
                'image3_location'   => '/images/canyoning3.jpg',
                'start' 			=> now(),
                'end' 				=> now(),
                'number_of_persons' => 1,
            ],
            [
                'id_category' 		=> 2,
                'id_type' 			=> 2,
                'id_city' 			=> 4,
                'id_region' 		=> 1,
                'id_country' 		=> 1,
                'name' 				=> 'Descente en Rafting',
                'description' 		=> "Sport d’eau vive, les descentes en rafting se pratiquent au sein des rapides à l’aide d’un raft qui est votre moyen de flotter sur l’eau. La chaleur que l’adrénaline vous procurera sera vite rafraîchie par l’eau des rapides. C’est une expérience qui se déroule dans une ambiance conviviale dû à l’entraide, elle se partage aisément entre amis ou en famille. Sélectionnez maintenant un stage de rafting près de chez vous.",
                'amount'			=> 40,
                'image1_location'   => '/images/rafting1.jpg',
                'image2_location'   => '/images/rafting2.jpg',
                'image3_location'   => '/images/rafting3.jpg',
                'start' 			=> now(),
                'end' 				=> now(),
                'number_of_persons' => 1,
            ],
            [
                'id_category' 		=> 3,
                'id_type' 			=> 2,
                'id_city' 			=> 3,
                'id_region' 		=> 1,
                'id_country' 		=> 1,
                'name' 				=> 'Escalade en plein nature à Gorge du Verdon',
                'description' 		=> "Les forêts de conifères environnants, les grands espaces, le calme apaisant de la nature, le chant des oiseaux, le contact avec la roche, le bruit d’une fontaine, l’écho des montagnes… L’ascension d’une paroi rocheuse permet d’être au plus près de la nature, une véritable bouffée d’oxygène. L’escalade est un exercice physique : travail de votre musculature, endurance, résistance articulaire. Vous grimpez donc dans un environnement naturel exceptionnel, pour à l’arrivée profiter d’une vue vous dédommageant des efforts fournis, ressentir une sensation d’épuisement et de sérénité, un sentiment agréable d’avoir accompli un exploit ! Convaincu ? Il ne vous reste plus qu’à enfiler votre casque et baudrier ! Si l’escalade de falaises vous impressionne, l’escalade de bloc (en salle) est une bonne alternative. Grâce aux précieux conseils du moniteur, apprenez les bases ou progressez dans une ambiance conviviale et détendue !",
                'amount'			=> 20,
                'image1_location'   => '/images/escalade1.jpg',
                'image2_location'   => '/images/escalade2.jpg',
                'image3_location'   => '/images/escalade3.jpg',
                'start' 			=> now(),
                'end' 				=> now(),
                'number_of_persons' => 1,
            ],
            [
                'id_category' 		=> 4,
                'id_type' 			=> 5,
                'id_city' 			=> 1,
                'id_region' 		=> 1,
                'id_country' 		=> 1,
                'name' 				=> 'Stage collectif de ski',
                'description' 		=> "Initiation ou perfectionnement au ski alpin, excursion au ski de randonnée, descente de piste noire, télémark, sortie Freestyle… La liste des possibilités est longue ! Les amateurs de ski intense seront servis en sensations fortes, mais également conquis par le panorama s’offrant à eux, à découvrir tout en dévalant la montagne, 2 en 1 n’est-ce pas formidable ! Grâce au moniteur, vous pourrez rapidement améliorer votre technique et apprendre l’utilisation correcte du matériel, indispensable pour progresser ! En famille ou entre amis, en privé ou en collectif, venez profiter du grand air frais et d’un ensoleillement maximal. Des moments de pur bonheur garantis !",
                'amount'			=> 70,
                'image1_location'   => '/images/ski1.jpg',
                'image2_location'   => '/images/ski2.jpg',
                'image3_location'   => '/images/ski3.jpg',
                'start' 			=> now(),
                'end' 				=> now(),
                'number_of_persons' => 1,
            ]
        ];
        DB::table('activities')->insert($Activity);
    }
}
